---
- name: Get mattermost.
  git:
    repo: "https://github.com/mattermost/mattermost-docker.git"
    dest: "{{ git_clone_dir }}"
    version: "master"

- name: Build docker image.
  shell: docker-compose build
  args:
    chdir: "{{ git_clone_dir }}"

- name: Add mattermost group.
  group:
    name: mattermost
    gid: 2000
    state: present

- name: Add mattermost user.
  user:
    name: mattermost
    uid: 2000
    group: mattermost

- name: Make mount directories.
  file:
    path: "{{ item }}"
    state: directory
    owner: mattermost
    group: mattermost
  with_items:
    - "{{ git_clone_dir }}/volumes/app/mattermost"
    - "{{ git_clone_dir }}/volumes/app/mattermost/data"
    - "{{ git_clone_dir }}/volumes/app/mattermost/logs"
    - "{{ git_clone_dir }}/volumes/app/mattermost/config"
    - "{{ git_clone_dir }}/volumes/app/mattermost/plugins"
    - "{{ git_clone_dir }}/volumes/app/mattermost/client-plugins"
  become: yes

- name: Start docker-compose.
  shell: docker-compose up -d
  args:
    chdir: "{{ git_clone_dir }}"
